upstream moto-api {
  server unix:///home/deploy/production/moto-admin/shared/tmp/sockets/moto-backend.sock fail_timeout=0;
}
server {
  listen 80;
  server_name api.motodesign.cn;
  return 301 https://$host$request_uri;
}

server {
  listen 443 ssl;
  server_name api.motodesign.cn;

  root /home/deploy/production/moto-admin/current/public;

  try_files $uri/index.html $uri.html $uri @moto-api;
  ssl_session_timeout 5m;
  ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
  ssl_ciphers ECDHE-RSA-AES128-GCM-SHA256:HIGH:!aNULL:!MD5:!RC4:!DHE;
  ssl_prefer_server_ciphers on;
  ssl_certificate /etc/letsencrypt/live/www.motodesign.cn/fullchain.pem; # managed by Certbot
  ssl_certificate_key /etc/letsencrypt/live/www.motodesign.cn/privkey.pem; # managed by Certbot
  location ~* \/(php|mysql|database|2php|wp)$ {
                #allow 127.0.0.1;
                deny all;
  }

 location /cable {
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "Upgrade";
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_pass http://moto-api;
  }

 location @moto-api {
      proxy_pass http://unix://home/deploy/production/moto-admin/shared/tmp/sockets/moto-backend.sock;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      # proxy_set_header X-Forwarded-Proto $scheme;
      proxy_set_header X-Forwarded-Ssl on; # required by Rails 5.1
      proxy_set_header Host $http_host;
      proxy_redirect off;
      proxy_set_header X-Forwarded-Proto https;
  }

  error_page 500 502 503 504 /500.html;
  client_max_body_size 4G;
  keepalive_timeout 10;

  access_log /var/log/nginx/moto-api.log;
  error_log /var/log/nginx/moto-api.log;
}