server {
  listen 80;
  listen [::]:80;
  server_name motodesign.cn www.motodesign.cn;  
  return 301 https://$host$request_uri;
}

server {
  listen 443 ssl http2;
  listen [::]:443 ssl http2;
  server_name motodesign.cn www.motodesign.cn;

  root /home/deploy/production/dist;
  index index.html;

  try_files $uri/index.html $uri.html;
  location / {
	  add_header Cache-Control "no-cache, no-store,max-age:0";
	  index index.html;
    try_files $uri $uri/ /index.html;		         
  }

  location /assets/ {
    expires modified 30d;
    add_header Surrogate-Control "public, max-age=86400";
    add_header Cache-Control "public, no-transform, max-age=86400";
  	alias /home/deploy/production/dist/assets/;
  }


  ssl_certificate /etc/letsencrypt/live/www.motodesign.cn/fullchain.pem; # managed by Certbot
	ssl_certificate_key /etc/letsencrypt/live/www.motodesign.cn/privkey.pem; # managed by Certbot
  
  ssl_session_cache shared:SSL:10m;
  ssl_session_timeout 10m;
  ssl_protocols TLSv1.2 TLSv1.3;
  ssl_ciphers 'ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384';
  ssl_prefer_server_ciphers on;

  location ~* \/(php|mysql|database|2php|wp)$ {
                #allow 127.0.0.1;
                deny all;
  }


  error_page 500 502 503 504 /500.html;
  client_max_body_size 4G;
  keepalive_timeout 10;

  access_log /var/log/nginx/moto.log;
  error_log /var/log/nginx/moto.log;
}